# Generated by Django 3.2.3 on 2021-12-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=15)),
                ('Celular', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=30)),
                ('Especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicio', models.CharField(max_length=30)),
                ('Especialidad', models.CharField(max_length=30)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Horario_inicio', models.TimeField()),
                ('Horario_fin', models.TimeField()),
                ('Descanso', models.CharField(max_length=30)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuarios')),
            ],
        ),
    ]
