# Generated by Django 3.2.7 on 2021-12-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=15)),
                ('Contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=30)),
                ('Especialidad', models.CharField(max_length=15)),
                ('Identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicio', models.CharField(max_length=30)),
                ('Especialidad', models.CharField(max_length=30)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Horas', models.DateTimeField()),
                ('Descanso', models.CharField(max_length=30)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuarios')),
            ],
        ),
    ]
