# Generated by Django 3.2.7 on 2021-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Identificacion',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Usuario',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Especialidad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ingreso',
        ),
    ]
