# Generated by Django 4.0 on 2021-12-09 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211208_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='Horas',
        ),
        migrations.AddField(
            model_name='turnos',
            name='Horario_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='Horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Usuario',
            field=models.CharField(max_length=15),
        ),
    ]
